### ISSUE TITLE
How you import ProtocolBuffer

### ISSUE THREAD

**Issue by pablopantaleon** [google/protorpc#8]
Hi, i'm new in this. I tried to run the project but give me an error in 

google.net.proto import ProtocolBuffer

i'm in win 8 with python 2.7.7

**Comment by quezak** [comment]
I have the same issue.
I tried to run [this example from docs](https://cloud.google.com/appengine/docs/python/tools/protorpc/#The_Hello_World_of_ProtoRPC)
The complete error I'm getting:
```
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    from protorpc import remote
  File "/usr/lib64/python3.4/site-packages/protorpc/remote.py", line 117, in <module>
    from . import protobuf
  File "/usr/lib64/python3.4/site-packages/protorpc/protobuf.py", line 41, in <module>
    from .google_imports import ProtocolBuffer
ImportError: cannot import name 'ProtocolBuffer'
```
Is there any workaround for this?

This happens on both my computers, running gentoo, one has python 3.4 and the other 3.5
protorpc version 0.11.1
protobuf-python version 3.0.0_beta3_p1
